missing '@' symbol while importing
Constellation-Labs/documentation-hub pull request #113
Opened 2024-09-03 07:02 UTC by cse-amarjeet

missing '@' symbol while importing "stardust-collective/dag4"

2024-09-03 07:51 UTC, A1811-qbite commented
@Ansenques

2024-09-03 09:26 UTC, A1811-qbite requested changes
@A1811-qbite

2024-09-03 09:26 UTC, A1811-qbite commented on hypergraph/guides/DAG4.js/01-dag4.md
> +const { dag4 } = require('@stardust-collective/dag4');
@A1811-qbite

2024-12-05 21:57 UTC, AlexBrandes approved these changes

2024-12-05 21:57 UTC, merged