Updating docs
Constellation-Labs/documentation-hub pull request #84
Opened 2024-04-29 18:35 UTC by IPadawans

2024-04-29 23:19 UTC, AlexBrandes requested changes
Apologies for so many comments - docs are hard. I think in general, we just need to zoom out from the technical details a little bit and make sure that the concepts are described clearly for newcomers that are starting with limited context.

- Would you check the Telemetry Dashboard section also? There's out of date info in there about how to start the old "monitoring" containers. 
- In the Developer Dashboard section, are we recommending the correct default ports? I think those changed in a previous version - should also update that repo if we haven't already.

2024-04-29 23:19 UTC, AlexBrandes commented on sdk/elements/03-hydra-cli.md
> +After these steps, the service restarts the node or layer and reintegrates it into the cluster.
I think this section needs to zoom out and describe what the service does at a high level. I don't think we need to mention PM2 or sudo privileges here. What does the service do? 

Something like... 
The service runs health checks on a regular interval and evaluates the metagraph cluster on a set of predefined or developer-created health criteria (restart-conditions). Restart conditions can target the whole cluster, a specific layer, or individual nodes to ensure that the metagraph is operating properly in each case. If an issue is detected, the service uses SSH to access the impacted node(s) and restart their process and rejoin them to the network.

2024-04-29 23:19 UTC, AlexBrandes commented on sdk/elements/03-hydra-cli.md
> +-   [metagraph-monitoring-service](https://github.com/Constellation-Labs/metagraph-monitoring-service-package)
What's the difference between these two repositories? I feel like these should be described separately.

2024-04-29 23:19 UTC, AlexBrandes commented on sdk/frameworks/currency/01-overview.md
> +```
Should we even recommend any versions earlier than the latest?

2024-04-30 12:09 UTC, IPadawans commented on sdk/frameworks/currency/01-overview.md
> +## Installation using giter8
Done

2024-04-30 12:10 UTC, IPadawans commented on sdk/frameworks/currency/01-overview.md
> +## Installation using metagraph examples
Done

2024-04-30 12:11 UTC, IPadawans commented on sdk/frameworks/currency/01-overview.md
> +The Currency Framework provides a fast and customizable way to launch a decentralized application (dApp) with native support for currency-related transactions. Unlike closed-loop systems such as smar
Done

2024-04-30 12:11 UTC, IPadawans commented on sdk/frameworks/currency/01-overview.md
> +By using this framework, developers gain the advantage of building and customizing their own applications, supported by a proven underlying framework. This saves significant effort in handling conven
Done

2024-04-30 12:12 UTC, IPadawans commented on sdk/frameworks/currency/01-overview.md
> +For optimal results, it is recommended to run this framework as part of a [Euclid Development Environment](https://chat.openai.com/sdk/elements/dev-environment) project. This environment manages the
Done

2024-04-30 12:13 UTC, IPadawans commented on sdk/frameworks/currency/01-overview.md
> +The Currency Framework can be distributed in several ways, including:
Done

2024-04-30 12:45 UTC, IPadawans commented on sdk/frameworks/currency/01-overview.md
> +Clone the [repository](https://github.com/Constellation-Labs/metagraph-examples) and select the desired example. Navigate to the example directory to proceed.
Yeah, we can remove the manual suggestion

2024-04-30 12:46 UTC, IPadawans commented on sdk/frameworks/currency/01-overview.md
> +:::
Done

2024-04-30 12:46 UTC, IPadawans commented on sdk/frameworks/currency/01-overview.md
> +
Updated

2024-04-30 12:47 UTC, IPadawans commented on sdk/frameworks/currency/02-data-api.md
> +The endpoint is designed to support multiple data types through a single access point, and these types are parsed within your application code. To accommodate different types of data, you should impl
Updated

2024-04-30 12:47 UTC, IPadawans commented on sdk/frameworks/currency/02-data-api.md
> +### OnChainState vs. CalculatedState
Done

2024-04-30 17:15 UTC, IPadawans commented on sdk/frameworks/currency/02-data-api.md
> +class OnChainState(updates: List[Update]) extends DataOnChainState
Updated

2024-04-30 17:15 UTC, IPadawans commented on sdk/frameworks/currency/02-data-api.md
> +Here one example of how to use it:
Updated

2024-04-30 17:20 UTC, IPadawans commented on sdk/frameworks/currency/02-data-api.md
> +This function updates the `calculatedState`. Below is an example of how to implement an in-memory update of `calculatedState`.
No this is a separated function, I've updated

2024-04-30 17:23 UTC, IPadawans commented on sdk/elements/03-hydra-cli.md
> +## Remote Monitoring
Moved

2024-07-08 22:32 UTC, AlexBrandes approved these changes

2024-07-08 22:34 UTC, merged